spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: metrics
springdoc:
  swagger-ui:
    path: /swagger-ui-doc.html